version: "3"

services:
    app:
        hostname: app
        build:
            dockerfile: Dockerfile
            context: .
        restart: always
        ports:
            - 8090:8090
        volumes:
            - ./:/app
        depends_on:
            - database
        networks:
            - balance
    database:
        hostname: database
        image: postgres:12.7
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./postgresql_data:/var/lib/postgresql/data
            - ./db.sql:/docker-entrypoint-initdb.d/db.sql
        networks:
            - balance
networks:
    balance:
        driver: bridge